// File generated by Antigravity based on google-services.json.
// Note: It is recommended to run `flutterfire configure` for a complete setup.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-HE0h21wNVn-7r3HYSdCLWkIv33kYE8U',
    appId: '1:525095142500:web:9dc5f00bb3414994650b71', // Estimated
    messagingSenderId: '525095142500',
    projectId: 'gpayhomeaccount',
    authDomain: 'gpayhomeaccount.firebaseapp.com',
    storageBucket: 'gpayhomeaccount.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-HE0h21wNVn-7r3HYSdCLWkIv33kYE8U',
    appId: '1:525095142500:android:9dc5f00bb3414994650b71',
    messagingSenderId: '525095142500',
    projectId: 'gpayhomeaccount',
    storageBucket: 'gpayhomeaccount.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-HE0h21wNVn-7r3HYSdCLWkIv33kYE8U',
    appId: '1:525095142500:ios:9dc5f00bb3414994650b71', // Estimated
    messagingSenderId: '525095142500',
    projectId: 'gpayhomeaccount',
    storageBucket: 'gpayhomeaccount.firebasestorage.app',
    iosBundleId: 'com.gpay.extractor.gpay_extractor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-HE0h21wNVn-7r3HYSdCLWkIv33kYE8U',
    appId: '1:525095142500:ios:9dc5f00bb3414994650b71', // Estimated
    messagingSenderId: '525095142500',
    projectId: 'gpayhomeaccount',
    storageBucket: 'gpayhomeaccount.firebasestorage.app',
    iosBundleId: 'com.gpay.extractor.gpay_extractor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-HE0h21wNVn-7r3HYSdCLWkIv33kYE8U',
    appId: '1:525095142500:web:9dc5f00bb3414994650b71', // Estimated
    messagingSenderId: '525095142500',
    projectId: 'gpayhomeaccount',
    authDomain: 'gpayhomeaccount.firebaseapp.com',
    storageBucket: 'gpayhomeaccount.firebasestorage.app',
  );
}
